/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Dimension;

/**
 *
 * @author DevLuisFF
 */
public class FrmMenu extends javax.swing.JFrame {

    
    public FrmMenu() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setLocationRelativeTo(null);
        this.setTitle("Menu - Billify");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jDesktopPane_menu = new javax.swing.JDesktopPane();
        background = new javax.swing.JPanel();
        BarraMenu = new javax.swing.JMenuBar();
        UsuariosMenu = new javax.swing.JMenu();
        NuevoUsuarioItem = new javax.swing.JMenuItem();
        GestionUsuarioItem = new javax.swing.JMenuItem();
        ProductosMenu = new javax.swing.JMenu();
        NuevoProductoItem = new javax.swing.JMenuItem();
        GestionProductoItem = new javax.swing.JMenuItem();
        ActualizarStockItem = new javax.swing.JMenuItem();
        ClientesMenu = new javax.swing.JMenu();
        NuevoClienteItem = new javax.swing.JMenuItem();
        GestionarClienteItem = new javax.swing.JMenuItem();
        CategoriasMenu = new javax.swing.JMenu();
        NuevaCategoriaItem = new javax.swing.JMenuItem();
        GestionarCategoriaItem = new javax.swing.JMenuItem();
        FacturarMenu = new javax.swing.JMenu();
        NuevaVentaItem = new javax.swing.JMenuItem();
        GestionarVentaItem = new javax.swing.JMenuItem();
        ReportesMenu = new javax.swing.JMenu();
        ReporteClientesItem = new javax.swing.JMenuItem();
        ReporteCategoriaItem = new javax.swing.JMenuItem();
        ReporteProductosItem = new javax.swing.JMenuItem();
        ReporteVentasItem = new javax.swing.JMenuItem();
        HistorialMenu = new javax.swing.JMenu();
        VerHistorialItem = new javax.swing.JMenuItem();
        CerrarMenu = new javax.swing.JMenu();
        cerrarItem = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane_menu.setForeground(new java.awt.Color(255, 255, 255));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${foreground}"), jDesktopPane_menu, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        background.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane_menu.add(background);
        background.setBounds(0, 0, 1200, 660);

        getContentPane().add(jDesktopPane_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 1200, 660));

        BarraMenu.setBackground(new java.awt.Color(255, 255, 255));
        BarraMenu.setBorder(null);

        UsuariosMenu.setBackground(new java.awt.Color(255, 255, 255));
        UsuariosMenu.setBorder(null);
        UsuariosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userblack16.png"))); // NOI18N
        UsuariosMenu.setText("Usuarios");
        UsuariosMenu.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        UsuariosMenu.setPreferredSize(new java.awt.Dimension(150, 30));

        NuevoUsuarioItem.setBackground(new java.awt.Color(255, 255, 255));
        NuevoUsuarioItem.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        NuevoUsuarioItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-add.png"))); // NOI18N
        NuevoUsuarioItem.setText("Nuevo Usuario");
        NuevoUsuarioItem.setBorder(null);
        UsuariosMenu.add(NuevoUsuarioItem);

        GestionUsuarioItem.setBackground(new java.awt.Color(255, 255, 255));
        GestionUsuarioItem.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        GestionUsuarioItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users-alt.png"))); // NOI18N
        GestionUsuarioItem.setText("Gestionar Usuarios");
        GestionUsuarioItem.setBorder(null);
        UsuariosMenu.add(GestionUsuarioItem);

        BarraMenu.add(UsuariosMenu);

        ProductosMenu.setBackground(new java.awt.Color(255, 255, 255));
        ProductosMenu.setBorder(null);
        ProductosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cube.png"))); // NOI18N
        ProductosMenu.setText("Productos");
        ProductosMenu.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        ProductosMenu.setPreferredSize(new java.awt.Dimension(150, 30));

        NuevoProductoItem.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        NuevoProductoItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        NuevoProductoItem.setText("Nuevo Producto");
        NuevoProductoItem.setBorder(null);
        NuevoProductoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoProductoItemActionPerformed(evt);
            }
        });
        ProductosMenu.add(NuevoProductoItem);

        GestionProductoItem.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        GestionProductoItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        GestionProductoItem.setText("Gestionar Producto");
        GestionProductoItem.setBorder(null);
        ProductosMenu.add(GestionProductoItem);

        ActualizarStockItem.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        ActualizarStockItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        ActualizarStockItem.setText("Actualizar Stock");
        ActualizarStockItem.setBorder(null);
        ProductosMenu.add(ActualizarStockItem);

        BarraMenu.add(ProductosMenu);

        ClientesMenu.setBackground(new java.awt.Color(255, 255, 255));
        ClientesMenu.setBorder(null);
        ClientesMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users-alt.png"))); // NOI18N
        ClientesMenu.setText("Clientes");
        ClientesMenu.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        ClientesMenu.setPreferredSize(new java.awt.Dimension(150, 30));

        NuevoClienteItem.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        NuevoClienteItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-add.png"))); // NOI18N
        NuevoClienteItem.setText("Nuevo Cliente");
        NuevoClienteItem.setBorder(null);
        ClientesMenu.add(NuevoClienteItem);

        GestionarClienteItem.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        GestionarClienteItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users-alt.png"))); // NOI18N
        GestionarClienteItem.setText("Gestionar Cliente");
        GestionarClienteItem.setBorder(null);
        ClientesMenu.add(GestionarClienteItem);

        BarraMenu.add(ClientesMenu);

        CategoriasMenu.setBackground(new java.awt.Color(255, 255, 255));
        CategoriasMenu.setBorder(null);
        CategoriasMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apps.png"))); // NOI18N
        CategoriasMenu.setText("Categorías");
        CategoriasMenu.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        CategoriasMenu.setPreferredSize(new java.awt.Dimension(150, 40));

        NuevaCategoriaItem.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        NuevaCategoriaItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        NuevaCategoriaItem.setText("Nueva Categoría ");
        NuevaCategoriaItem.setBorder(null);
        NuevaCategoriaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaCategoriaItemActionPerformed(evt);
            }
        });
        CategoriasMenu.add(NuevaCategoriaItem);

        GestionarCategoriaItem.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        GestionarCategoriaItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        GestionarCategoriaItem.setText("Gestionar Categoría");
        GestionarCategoriaItem.setBorder(null);
        GestionarCategoriaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarCategoriaItemActionPerformed(evt);
            }
        });
        CategoriasMenu.add(GestionarCategoriaItem);

        BarraMenu.add(CategoriasMenu);

        FacturarMenu.setBackground(new java.awt.Color(255, 255, 255));
        FacturarMenu.setBorder(null);
        FacturarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document.png"))); // NOI18N
        FacturarMenu.setText("Facturar");
        FacturarMenu.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        FacturarMenu.setPreferredSize(new java.awt.Dimension(150, 30));

        NuevaVentaItem.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        NuevaVentaItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        NuevaVentaItem.setText("Nueva Venta");
        NuevaVentaItem.setBorder(null);
        FacturarMenu.add(NuevaVentaItem);

        GestionarVentaItem.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        GestionarVentaItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        GestionarVentaItem.setText("Gestionar Ventas");
        GestionarVentaItem.setBorder(null);
        FacturarMenu.add(GestionarVentaItem);

        BarraMenu.add(FacturarMenu);

        ReportesMenu.setBackground(new java.awt.Color(255, 255, 255));
        ReportesMenu.setBorder(null);
        ReportesMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document-signed.png"))); // NOI18N
        ReportesMenu.setText("Reportes");
        ReportesMenu.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        ReportesMenu.setPreferredSize(new java.awt.Dimension(150, 30));

        ReporteClientesItem.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        ReporteClientesItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users-alt.png"))); // NOI18N
        ReporteClientesItem.setText("Reportes Clientes");
        ReporteClientesItem.setBorder(null);
        ReportesMenu.add(ReporteClientesItem);

        ReporteCategoriaItem.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        ReporteCategoriaItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apps.png"))); // NOI18N
        ReporteCategoriaItem.setText("Reportes Categoria");
        ReporteCategoriaItem.setBorder(null);
        ReportesMenu.add(ReporteCategoriaItem);

        ReporteProductosItem.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        ReporteProductosItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cube.png"))); // NOI18N
        ReporteProductosItem.setText("Reportes Productos");
        ReporteProductosItem.setBorder(null);
        ReportesMenu.add(ReporteProductosItem);

        ReporteVentasItem.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        ReporteVentasItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping-cart.png"))); // NOI18N
        ReporteVentasItem.setText("Reportes Ventas");
        ReporteVentasItem.setBorder(null);
        ReportesMenu.add(ReporteVentasItem);

        BarraMenu.add(ReportesMenu);

        HistorialMenu.setBackground(new java.awt.Color(255, 255, 255));
        HistorialMenu.setBorder(null);
        HistorialMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stats.png"))); // NOI18N
        HistorialMenu.setText("Historial");
        HistorialMenu.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        HistorialMenu.setPreferredSize(new java.awt.Dimension(150, 30));

        VerHistorialItem.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        VerHistorialItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stats.png"))); // NOI18N
        VerHistorialItem.setText("Ver Historial");
        VerHistorialItem.setBorder(null);
        HistorialMenu.add(VerHistorialItem);

        BarraMenu.add(HistorialMenu);

        CerrarMenu.setBackground(new java.awt.Color(255, 255, 255));
        CerrarMenu.setBorder(null);
        CerrarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross-circle.png"))); // NOI18N
        CerrarMenu.setText("Cerrar ");
        CerrarMenu.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        CerrarMenu.setPreferredSize(new java.awt.Dimension(150, 30));

        cerrarItem.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        cerrarItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross-circle.png"))); // NOI18N
        cerrarItem.setText("Cerrar");
        cerrarItem.setBorder(null);
        CerrarMenu.add(cerrarItem);

        BarraMenu.add(CerrarMenu);

        setJMenuBar(BarraMenu);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoProductoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoProductoItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoProductoItemActionPerformed

    private void NuevaCategoriaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaCategoriaItemActionPerformed
        InterCategoria interCategoria = new InterCategoria();
        jDesktopPane_menu.add(interCategoria);
        interCategoria.setVisible(true);
    }//GEN-LAST:event_NuevaCategoriaItemActionPerformed

    private void GestionarCategoriaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarCategoriaItemActionPerformed
        InterGestionarCategoria interGestionarCategoria = new InterGestionarCategoria();
        jDesktopPane_menu.add(interGestionarCategoria);
        interGestionarCategoria.setVisible(true);
    }//GEN-LAST:event_GestionarCategoriaItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActualizarStockItem;
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenu CategoriasMenu;
    private javax.swing.JMenu CerrarMenu;
    private javax.swing.JMenu ClientesMenu;
    private javax.swing.JMenu FacturarMenu;
    private javax.swing.JMenuItem GestionProductoItem;
    private javax.swing.JMenuItem GestionUsuarioItem;
    private javax.swing.JMenuItem GestionarCategoriaItem;
    private javax.swing.JMenuItem GestionarClienteItem;
    private javax.swing.JMenuItem GestionarVentaItem;
    private javax.swing.JMenu HistorialMenu;
    private javax.swing.JMenuItem NuevaCategoriaItem;
    private javax.swing.JMenuItem NuevaVentaItem;
    private javax.swing.JMenuItem NuevoClienteItem;
    private javax.swing.JMenuItem NuevoProductoItem;
    private javax.swing.JMenuItem NuevoUsuarioItem;
    private javax.swing.JMenu ProductosMenu;
    private javax.swing.JMenuItem ReporteCategoriaItem;
    private javax.swing.JMenuItem ReporteClientesItem;
    private javax.swing.JMenuItem ReporteProductosItem;
    private javax.swing.JMenuItem ReporteVentasItem;
    private javax.swing.JMenu ReportesMenu;
    private javax.swing.JMenu UsuariosMenu;
    private javax.swing.JMenuItem VerHistorialItem;
    private javax.swing.JPanel background;
    private javax.swing.JMenuItem cerrarItem;
    private javax.swing.JDesktopPane jDesktopPane_menu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
