/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Ctrl_Categoria;
import modelo.Categoria;

/**
 *
 * @author DevLuisFF
 */
public class InterCategoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterCategoria
     */
    public InterCategoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        titulolabel = new javax.swing.JLabel();
        descripcioncategorialabel = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        btnguardar = new javax.swing.JPanel();
        guardarlabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setIconifiable(true);

        Background.setBackground(new java.awt.Color(255, 255, 255));

        titulolabel.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        titulolabel.setText("Nueva Categoría");

        descripcioncategorialabel.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        descripcioncategorialabel.setText("Descripción categoría:");

        txt_descripcion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnguardar.setBackground(new java.awt.Color(255, 255, 255));
        btnguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        guardarlabel.setBackground(new java.awt.Color(255, 255, 255));
        guardarlabel.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        guardarlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guardarlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disk.png"))); // NOI18N
        guardarlabel.setText("Guardar");
        guardarlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarlabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnguardarLayout = new javax.swing.GroupLayout(btnguardar);
        btnguardar.setLayout(btnguardarLayout);
        btnguardarLayout.setHorizontalGroup(
            btnguardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guardarlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
        );
        btnguardarLayout.setVerticalGroup(
            btnguardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guardarlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(titulolabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(descripcioncategorialabel)
                        .addGap(18, 18, 18)
                        .addComponent(txt_descripcion)))
                .addContainerGap())
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulolabel)
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcioncategorialabel)
                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarlabelMouseClicked
        Categoria categoria = new Categoria();
        Ctrl_Categoria controlCategoria = new Ctrl_Categoria();

        //validacion de campos vacios
        if (txt_descripcion.getText().isEmpty()) {
            FrmCompletarCampos frmCompletarCampos = new FrmCompletarCampos();
            frmCompletarCampos.setVisible(true);
        } else {
            if (!controlCategoria.existeCategoria(txt_descripcion.getText().trim())) {
                categoria.setDescripcion(txt_descripcion.getText().trim());
                categoria.setEstado(1);
                if (controlCategoria.guardar(categoria)) {
                    FrmOperacionExitosa frmOperacionExitosa = new FrmOperacionExitosa();
                    frmOperacionExitosa.setVisible(true);
                } else {
                    FrmErrorOperacion frmErrorOperacion = new FrmErrorOperacion();
                    frmErrorOperacion.setVisible(true);
                }
            } else {
                FrmErrorOperacion frmErrorOperacion = new FrmErrorOperacion();
                frmErrorOperacion.setVisible(true);
            }

        }
        //limpiar el campo descripcion
        txt_descripcion.setText("");
    }//GEN-LAST:event_guardarlabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel btnguardar;
    private javax.swing.JLabel descripcioncategorialabel;
    private javax.swing.JLabel guardarlabel;
    private javax.swing.JLabel titulolabel;
    private javax.swing.JTextField txt_descripcion;
    // End of variables declaration//GEN-END:variables
}
