/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import static Vista.FrmDashboard.Content;
import java.awt.BorderLayout;

/**
 *
 * @author DevLuisFF
 */
public class ClientesPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClientesPanel
     */
    public ClientesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        titulolabel = new javax.swing.JLabel();
        nombrelabel = new javax.swing.JLabel();
        apellidolabel = new javax.swing.JLabel();
        cedulalabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        BtnGestionarClientes = new javax.swing.JButton();
        Nombretxt = new javax.swing.JTextField();
        Apellidotxt = new javax.swing.JTextField();
        Cedulatxt = new javax.swing.JTextField();
        Telefonotxt = new javax.swing.JTextField();
        Direcciontxt = new javax.swing.JTextField();

        Background.setBackground(new java.awt.Color(255, 255, 255));

        titulolabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        titulolabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clienteBlack16.png"))); // NOI18N
        titulolabel.setText("Nuevo Cliente");

        nombrelabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombrelabel.setText("Nombre:");

        apellidolabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        apellidolabel.setText("Apellido:");

        cedulalabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cedulalabel.setText("Cédula:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Teléfono:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Dirección:");

        BtnGuardar.setBackground(new java.awt.Color(0, 110, 144));
        BtnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disk.png"))); // NOI18N
        BtnGuardar.setText("Guardar");

        BtnGestionarClientes.setBackground(new java.awt.Color(0, 110, 144));
        BtnGestionarClientes.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        BtnGestionarClientes.setForeground(new java.awt.Color(255, 255, 255));
        BtnGestionarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/floppy-disk-pen.png"))); // NOI18N
        BtnGestionarClientes.setText("Gestión Clientes");
        BtnGestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGestionarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulolabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombrelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apellidolabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cedulalabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombretxt)
                            .addComponent(Apellidotxt)
                            .addComponent(Cedulatxt)
                            .addComponent(Telefonotxt)
                            .addComponent(Direcciontxt))))
                .addContainerGap())
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(BtnGestionarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulolabel)
                .addGap(41, 41, 41)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrelabel)
                    .addComponent(Nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidolabel)
                    .addComponent(Apellidotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulalabel)
                    .addComponent(Cedulatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Telefonotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Direcciontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar)
                    .addComponent(BtnGestionarClientes))
                .addGap(159, 159, 159))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGestionarClientesActionPerformed
        GestionarClientePanel gestionarClientePanel = new GestionarClientePanel();
        gestionarClientePanel.setSize(752, 436);
        gestionarClientePanel.setLocation(0, 0);
        FrmDashboard.Content.removeAll();
        Content.add(gestionarClientePanel, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }//GEN-LAST:event_BtnGestionarClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellidotxt;
    private javax.swing.JPanel Background;
    private javax.swing.JButton BtnGestionarClientes;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JTextField Cedulatxt;
    private javax.swing.JTextField Direcciontxt;
    private javax.swing.JTextField Nombretxt;
    private javax.swing.JTextField Telefonotxt;
    private javax.swing.JLabel apellidolabel;
    private javax.swing.JLabel cedulalabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nombrelabel;
    private javax.swing.JLabel titulolabel;
    // End of variables declaration//GEN-END:variables
}
